export { Singleton, OneShot, Inject, Select, OnDispose } from './decorators'
export { factoryOf, factoriesOf } from './factory'
export { keyOf } from './keyOf'
export { selectorOf } from './selectorOf'
export type { Constructor, ServiceToken } from './types'
export * from './errors'
